conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: raw
  root: ./data/samples/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 64
    intensity: 0.025
  noise:
    name: gaussian
    sigma: 0.01
